### ISSUE TITLE
mapOptions.areas can't replace my map areas when updating it with replaceOptions = true

### ISSUE THREAD

**Issue by eslammahgoub** [neveldo/jQuery-Mapael#218] opened 2016-04-04 13:48 UTC
I use Mapael  Version: 2.0.0-dev
Here my update option 
`var newupdate = {
      mapOptions: {
        areas : {}
      },
      replaceOptions : false,
    };
`
when I do that it not replace the areas with new one it extend with the old areas options I want to replace the map areas options with new one any help

**Comment by neveldo** [comment] 2016-04-04 22:13
Hello @eslammahgoub ,

Could you provide a little JSFiddle example of your work ? You said you have set `replaceOptions : false` instead of `replaceOptions : true` .

**Comment by eslammahgoub** [comment] 2016-04-04 22:19
Sorry but when i set replaceOptions : true it will remove all the default option even the legend; what i asked for is to replace just the areas option with new one "replaced not extend it"

**Comment by Samjin** [comment] 2016-10-31 00:43
I am having the exact same problem.

**Comment by neveldo** [comment] 2016-10-31 11:13
Hello @Samjin ,

The issue is not clear to me, could you provide a JSFiddle example of your code that highlights your issue , and explain what you want to achieve ?

**Comment by indigo-sam** [comment] 2016-11-03 22:05
HI Neveldo, I figured out how to update mapOption. The issue was my newObj ={} didn't match the properties hireachy correctly. I started from map = {} insteadof newObj = { map:{ } }.

**Comment by Indigo744** [comment] 2017-10-03 20:16
As stated in the help file, `opt.replaceOptions` option will _entirely replace current map options_.
Which means `opt.mapOptions` will extends the default options (actually in a similar fashion to the map creation) and replace all current options.

What you usually want to do is simply passing new options.
If you want to replace option, simply pass a new value for a specific area/plot/link (or defaultAttr).

I am closing this. Feel free to reopen if you need help.

**Closed by Indigo744** 2017-10-03 20:16 UTC
